/**
 * This file is autogenerated. Do not edit by hand — run `pnpm generate`.
 *
 * Non-local chain deployments live here; local (chainId 31337)
 * deployments live in `./ConfidentialPayroll.local.ts` (gitignored) and are merged in
 * at module load. Import by name: `import { ConfidentialPayroll } from "~~/contracts/ConfidentialPayroll";`
 */
import type { ContractDeployment } from "~~/utils/contract";
import { ConfidentialPayroll as ConfidentialPayroll_LOCAL } from "./ConfidentialPayroll.local";

const REMOTE = {
  11155111: {
    address: "0x32B413C9F6F274bA13A7978C467cDb3C2C833ead",
    abi: [
      {
        type: "constructor",
        inputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "receive",
        stateMutability: "payable",
      },
      {
        type: "function",
        name: "confidentialProtocolId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "employer",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "fulfillClaim",
        inputs: [
          {
            name: "requestId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "handlesList",
            type: "bytes32[]",
            internalType: "bytes32[]",
          },
          {
            name: "abiEncodedCleartexts",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "decryptionProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "getEmployeeCount",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getEmployees",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address[]",
            internalType: "address[]",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getSalary",
        inputs: [
          {
            name: "employee",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "isClaimFulfilled",
        inputs: [
          {
            name: "requestId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bool",
            internalType: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "isEmployee",
        inputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bool",
            internalType: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "removeEmployee",
        inputs: [
          {
            name: "employee",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "requestClaim",
        inputs: [],
        outputs: [
          {
            name: "requestId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "setSalary",
        inputs: [
          {
            name: "employee",
            type: "address",
            internalType: "address",
          },
          {
            name: "inputHandle",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "treasuryBalance",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "withdrawTreasury",
        inputs: [
          {
            name: "amount",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "ClaimPaid",
        inputs: [
          {
            name: "employee",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "amount",
            type: "uint64",
            indexed: false,
            internalType: "uint64",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "ClaimRequested",
        inputs: [
          {
            name: "employee",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "requestId",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "EmployeeAdded",
        inputs: [
          {
            name: "employee",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "EmployeeRemoved",
        inputs: [
          {
            name: "employee",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "PublicDecryptionVerified",
        inputs: [
          {
            name: "handlesList",
            type: "bytes32[]",
            indexed: false,
            internalType: "bytes32[]",
          },
          {
            name: "abiEncodedCleartexts",
            type: "bytes",
            indexed: false,
            internalType: "bytes",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "SalaryUpdated",
        inputs: [
          {
            name: "employee",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "error",
        name: "ClaimAlreadyFulfilled",
        inputs: [],
      },
      {
        type: "error",
        name: "ClaimNotFound",
        inputs: [],
      },
      {
        type: "error",
        name: "InsufficientTreasury",
        inputs: [],
      },
      {
        type: "error",
        name: "InvalidKMSSignatures",
        inputs: [],
      },
      {
        type: "error",
        name: "NoSalarySet",
        inputs: [],
      },
      {
        type: "error",
        name: "NotEmployer",
        inputs: [],
      },
      {
        type: "error",
        name: "SenderNotAllowedToUseHandle",
        inputs: [
          {
            name: "handle",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        type: "error",
        name: "TransferFailed",
        inputs: [],
      },
      {
        type: "error",
        name: "ZamaProtocolUnsupported",
        inputs: [],
      },
    ],
    deployedOnBlock: 10819692,
  },
} as const;

export const ConfidentialPayroll = {
  ...REMOTE,
  ...ConfidentialPayroll_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
